import React from 'react'

export const metadata = {
    title: "ISTAD - Setting",
    description: "Generated by create next app",
  }
const Setting = () => {
  return (
    <div  className='text-3xl text-center'>Setting page</div>
  )
}

export default Setting