import React from 'react'
export const metadata = {
  title: "ISTAD - Dashboard",
  description: "Generated by create next app",
}

const DashboardPage = () => {
  // if(!session){
  //   throw new Error('You must be authenticated')
  // }
  return (

    <h1 className='text-3xl text-center'>hello</h1>


  )
}

export default DashboardPage