import React from 'react'

export const metadata = {
    title: "ISTAD -Analytic",
    description: "Generated by create next app",

  }
const page = () => {
  return (
    <div className='text-3xl text-center'>page analytic</div>
  )
}

export default page